version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: luxuria_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: luxuria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Luxuria_BE
      dockerfile: Dockerfile
    container_name: luxuria_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/luxuria?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8086:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./Luxuria_FE
      dockerfile: Dockerfile
    container_name: luxuria_frontend
    restart: always
    ports:
      - "5173:80"

volumes:
  db_data:
